name: Deploy to VPS

on:
 push:
   branches:
     - master  

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up SSH
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

     - name: Deploy to VPS
       run: |
         ssh -o StrictHostKeyChecking=no deployer-elam@${{ secrets.VPS_HOST }} << 'EOF'
           cd /var/www/my-apps/parika-app-api
           git pull origin master  
         EOF
